// frontend/src/components/about/TAndCText.vue
<!--
  - KodeBlox Copyright 2020 Sayak Mukhopadhyay
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - http: //www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<template>
    <div>
        <p>
            Welcome to my website. If you continue to browse and use this website, you are agreeing to comply with and be
            bound by the following terms and conditions of use, which together with my privacy policy govern Elite BGS's
            relationship with you in relation to this website. If you disagree with any part of these terms and conditions,
            please do not use my website.
        </p>
        <p>
            The term 'Elite BGS' or 'me' or 'my' or 'I' refers to the owner of the website. The term 'you' refers to the user or
            viewer of my website.
        </p>
        <p>The use of this website is subject to the following terms of use:</p>
        <ol>
            <li>The content of the pages of this website is for your general information and use only. It is subject to
                change without notice.
            </li>
            <li>
                This website uses cookies to manage sessions. No other data is tracked using cookies.
            </li>
            <li>
                Neither I nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
                performance, completeness or suitability of the information and materials found or offered on this website
                for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or
                errors and I expressly exclude liability for any such inaccuracies or errors to the fullest extent
                permitted by law.
            </li>
            <li>
                Your use of any information or materials on this website is entirely at your own risk, for which I shall
                not be liable. It shall be your own responsibility to ensure that any products, services or information
                available through this website meet your specific requirements.
            </li>
            <li>
                All product names, logos, and brands are property of their respective owners. All company, product and
                service names used in this website are for identification purposes only. Use of these names, logos, and
                brands does not imply endorsement or affiliation.
            </li>
            <li>
                From time to time this website may also include links to other websites. These links are provided for your
                convenience to provide further information. They do not signify that we endorse the website(s). We have no
                responsibility for the content of the linked website(s).
            </li>
        </ol>
    </div>
</template>

<script>
export default {
  name: 'TAndCText'
}
</script>

<style scoped>

</style>

// src/app/about/tandc-text.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-tandc-text',
    templateUrl: './tandc-text.component.html'
})
export class TandCTextComponent { }

<div>
    <p>
        Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be
        bound by the following terms and conditions of use, which together with our privacy policy govern Elite BGS's
        relationship with you in relation to this website. If you disagree with any part of these terms and conditions,
        please do not use our website.
    </p>
    <p>
        The term 'Elite BGS' or 'me' or 'I' refers to the owner of the website. The term 'you' refers to the user or
        viewer of our website.
    </p>
    <p>The use of this website is subject to the following terms of use:</p>
    <ol>
        <li>The content of the pages of this website is for your general information and use only. It is subject to
            change without notice.
        </li>
        <li>
            This website uses cookies to manage sessions. No other data is tracked using cookies.
        </li>
        <li>
            Neither I nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
            performance, completeness or suitability of the information and materials found or offered on this website
            for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or
            errors and I expressly exclude liability for any such inaccuracies or errors to the fullest extent
            permitted by law.
        </li>
        <li>
            Your use of any information or materials on this website is entirely at your own risk, for which I shall
            not be liable. It shall be your own responsibility to ensure that any products, services or information
            available through this website meet your specific requirements.
        </li>
        <li>
            All product names, logos, and brands are property of their respective owners. All company, product and
            service names used in this website are for identification purposes only. Use of these names, logos, and
            brands does not imply endorsement or affiliation.
        </li>
        <li>
            From time to time this website may also include links to other websites. These links are provided for your
            convenience to provide further information. They do not signify that we endorse the website(s). We have no
            responsibility for the content of the linked website(s).
        </li>
    </ol>
</div>
