// frontend/src/app/about/disclaimer-text.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-disclaimer-text',
    templateUrl: './disclaimer-text.component.html'
})
export class DisclaimerTextComponent { }

<div>
    <p>
        This website is not an official tool for the game <a href="https://www.elitedangerous.com/">Elite Dangerous</a>
        and is not affiliated with <a href="https://frontier.co.uk/">Frontier Developments</a>. All information
        provided is based on publicly available information and may not be entirely accurate. Elite BGS was created
        using assets and imagery from Elite Dangerous, with the permission of Frontier Developments plc, for
        non-commercial purposes. It is not endorsed by nor reflects the views or opinions of Frontier Developments and
        no employee of Frontier Developments was involved in the making of it.
    </p>
    <p>
        The information contained in this website is for general information purposes only. The information is provided
        by Elite BGS and while I endeavour to keep the information up to date and correct, I make no representations or
        warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or
        availability with respect to the website or the information, products, services, or related graphics contained
        on the website for any purpose. Any reliance you place on such information is therefore strictly at your own
        risk.
    </p>
    <p>
        In no event will I be liable for any loss or damage including without limitation, indirect or consequential
        loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in
        connection with, the use of this website.
    </p>
    <p>
        Through this website you are able to link to other websites which are not under the control of Elite BGS. I
        have no control over the nature, content and availability of those sites. The inclusion of any links does not
        necessarily imply a recommendation or endorse the views expressed within them.
    </p>
    <p>
        Every effort is made to keep the website up and running smoothly. However, Elite BGS takes no responsibility
        for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond my
        control.
    </p>
</div>

// frontend/src/components/about/DisclaimerText.vue
<!--
  - KodeBlox Copyright 2020 Sayak Mukhopadhyay
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - http: //www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<template>
  <div>
    <p>
      This website is not an official tool for the game
      <a href="https://www.elitedangerous.com/">Elite Dangerous</a> and is not affiliated with
      <a href="https://frontier.co.uk/">Frontier Developments</a>. All information provided is based on publicly
      available information and may not be entirely accurate. Elite BGS was created using assets and imagery from Elite
      Dangerous, with the permission of Frontier Developments plc, for non-commercial purposes. It is not endorsed by
      nor reflects the views or opinions of Frontier Developments and no employee of Frontier Developments was involved
      in the making of it.
    </p>
    <p>
      The information contained in this website is for general information purposes only. The information is provided by
      Elite BGS and while I endeavour to keep the information up to date and correct, I make no representations or
      warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or
      availability with respect to the website or the information, products, services, or related graphics contained on
      the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
    </p>
    <p>
      In no event will I be liable for any loss or damage including without limitation, indirect or consequential loss
      or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection
      with, the use of this website.
    </p>
    <p>
      Through this website you are able to link to other websites which are not under the control of Elite BGS. I have
      no control over the nature, content and availability of those sites. The inclusion of any links does not
      necessarily imply a recommendation or endorse the views expressed within them.
    </p>
    <p>
      Every effort is made to keep the website up and running smoothly. However, Elite BGS takes no responsibility for,
      and will not be liable for, the website being temporarily unavailable due to technical issues beyond my control.
    </p>
  </div>
</template>

<script>
export default {
  name: 'DisclaimerText'
}
</script>

<style scoped></style>
