// frontend/src/app/main/factions/faction-view.component.ts
import { AfterViewInit, Component, HostBinding, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Title } from '@angular/platform-browser';
import { FactionsService } from '../../services/factions.service';
import { AuthenticationService } from '../../services/authentication.service';
import { IngameIdsService } from '../../services/ingameIds.service';
import { ThemeService } from '../../services/theme.service';
import { StringHandlers } from '../../utilities/stringHandlers';
import { EBGSFactionConflict, EBGSFactionSchemaDetailed, EBGSUser, IngameIdsSchema } from '../../typings';
import * as moment from 'moment';
import { Subject } from 'rxjs';
import { debounceTime, switchMap } from 'rxjs/operators';
import { ClrDatagrid } from '@clr/angular';

@Component({
    selector: 'app-faction-view',
    templateUrl: './faction-view.component.html'
})
export class FactionViewComponent implements OnInit, AfterViewInit {
    @HostBinding('class.content-area') contentArea = true;
    @ViewChild(ClrDatagrid) datagrid: ClrDatagrid;
    isAuthenticated: boolean;
    factionData: EBGSFactionSchemaDetailed;
    systemsPresence: number;
    systemsControlled: number;
    conflicts: EBGSFactionConflict[] = [];
    successAlertState = false;
    failureAlertState = false;
    fromDateFilter = new Date(Date.now() - 10 * 24 * 60 * 60 * 1000);
    toDateFilter = new Date(Date.now());
    dateFilterSubject = new Subject<any>();
    dateFilter$ = this.dateFilterSubject.asObservable();
    daysGap = 0;
    chartLoading = false;
    user: EBGSUser;
    FDevIDs: IngameIdsSchema;

    constructor(
        private factionService: FactionsService,
        private route: ActivatedRoute,
        private router: Router,
        private authenticationService: AuthenticationService,
        private titleService: Title,
        private ingameIdsService: IngameIdsService,
        private themeService: ThemeService
    ) {
    }

    ngAfterViewInit() {
        this.themeService.theme$.subscribe(() => {
            this.datagrid.resize();
        });
    }

    async ngOnInit() {
        this.checkRedirect();
        this.getAuthentication();
        this.FDevIDs = await this.ingameIdsService.getAllIds().toPromise();
        this.chartLoading = true;
        this.updateFaction((await this.getFactionData())[0]);
        this.chartLoading = false;
        this.dateFilter$
            .pipe(debounceTime(300))
            .pipe(switchMap(() => {
                this.chartLoading = true;
                return this.getFactionData();
            }))
            .subscribe(faction => {
                this.updateFaction(faction[0]);
                this.chartLoading = false;
            });
    }

    checkRedirect() {
        const routerParam = this.route.snapshot.paramMap.get('factionId')
        if (routerParam.startsWith('eddbId-')) {
            this.factionService.getFactionIdByEDDBId(routerParam.slice(7)).subscribe(factions => {
                this.router.navigateByUrl('/faction/' + factions.docs[0]._id)
            })
        }
    }

    async getFactionData(): Promise<EBGSFactionSchemaDetailed[]> {
        return await this.factionService
            .parseFactionDataId([this.route.snapshot.paramMap.get('factionId')], this.fromDateFilter, this.toDateFilter);
    }

    updateFaction(faction: EBGSFactionSchemaDetailed) {
        this.daysGap = moment(this.toDateFilter).diff(moment(this.fromDateFilter), 'days');
        this.factionData = faction;
        this.factionData.government = StringHandlers.titlify(this.factionData.government);
        this.factionData.allegiance = StringHandlers.titlify(this.factionData.allegiance);
        this.factionData.faction_presence.forEach(system => {
            system.state = this.FDevIDs.state[system.state].name;
            system.happiness = system.happiness ? this.FDevIDs.happiness[system.happiness].name : '';
            system.active_states = system.active_states ? system.active_states : [];
            system.active_states.forEach(state => {
                state.state = this.FDevIDs.state[state.state].name;
            });
            system.pending_states.forEach(state => {
                state.state = this.FDevIDs.state[state.state].name;
            });
            system.recovering_states.forEach(state => {
                state.state = this.FDevIDs.state[state.state].name;
            });
            if (system.conflicts) {
                system.conflicts.forEach(conflict => {
                    conflict.system_id = system.system_id;
                    conflict.system_name = system.system_name;
                });
            }
        });
        this.conflicts = this.factionData.faction_presence.reduce((acc, system) => {
            return acc.concat(system.conflicts);
        }, [] as EBGSFactionConflict[]);
        this.systemsPresence = this.factionData.faction_presence.length;
        this.factionData.faction_presence.forEach(system => {
            if (system.system_details.controlling_minor_faction_id === this.factionData._id) {
                system.controlling = true;
            }
        })
        this.systemsControlled = this.factionData.faction_presence.reduce((count, system) => {
            if (system.controlling) {
                return count + 1;
            } else {
                return count;
            }
        }, 0);
        this.titleService.setTitle(this.factionData.name + ' - Elite BGS');
    }

    getAuthentication() {
        this.authenticationService
            .isAuthenticated()
            .subscribe(status => {
                this.isAuthenticated = status;
                if (this.isAuthenticated) {
                    this.getUser();
                } else {
                    this.user = {} as EBGSUser;
                }
            });
    }

    getUpdatedAtFormatted(updatedAt) {
        return {
            time: moment(updatedAt).utc().format('ddd, MMM D, HH:mm:ss'),
            fromNow: moment(updatedAt).fromNow(true),
            ageFlag: moment(Date.now()).diff(moment(updatedAt), 'days', true) - 1
        }
    }

    monitor() {
        this.authenticationService
            .addFactions([this.factionData.name])
            .subscribe(status => {
                if (status === true) {
                    this.successAlertState = true;
                    setTimeout(() => {
                        this.successAlertState = false;
                    }, 3000);
                } else {
                    this.failureAlertState = true;
                    setTimeout(() => {
                        this.failureAlertState = false
                    }, 3000);
                }
            });
    }

    getUser() {
        this.authenticationService
            .getUser()
            .subscribe(user => {
                this.user = user;
            });
    }

    fromDateChange(date: Date) {
        this.fromDateFilter = date;
        this.dateFilterSubject.next();
    }

    toDateChange(date: Date) {
        this.toDateFilter = date;
        this.dateFilterSubject.next();
    }
}

<div>
    <clr-alert [clrAlertType]="'alert-success'" [clrAlertClosable]="false" [clrAlertClosed]="!successAlertState">
        <div clr-alert-item class="alert-item">
            <span class="alert-text">
                Added {{factionData?.name}} as a monitored Faction.
            </span>
        </div>
    </clr-alert>
    <clr-alert [clrAlertType]="'alert-danger'" [clrAlertClosable]="false" [clrAlertClosed]="!failureAlertState">
        <div clr-alert-item class="alert-item">
            <span class="alert-text">
                {{factionData?.name}} could not be added as a monitored Faction due to some error.
            </span>
        </div>
    </clr-alert>
    <h1>{{factionData?.name}}</h1>
    <ng-container *ngIf="user && user.access === 2; then banTemplate; else accessTemplate"></ng-container>
    <ng-template #banTemplate>
        <h1>You have been Banned from the website.</h1>
        <p>Please contact the developer for further details</p>
    </ng-template>
    <ng-template #accessTemplate>
        <ng-container *ngIf="user">
            <div class="btn-group btn-primary">
                <button (click)="monitor()" class="btn btn-primary"
                    [disabled]="!isAuthenticated || isAuthenticated === undefined">Monitor
                    Faction</button>
                <a class="btn btn-primary" href="https://eddb.io/faction/{{factionData?.eddb_id}}"
                    target="_blank">EDDB</a>
            </div>
        </ng-container>
    </ng-template>
    <div class="clr-row data-description">
        <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-4 clr-col-xl-3">
            <b>Government : </b>{{factionData?.government}}
        </div>
        <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-4 clr-col-xl-3">
            <b>Allegiance : </b>{{factionData?.allegiance}}
        </div>
        <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-4 clr-col-xl-3">
            <b>Systems Presence : </b>{{systemsPresence}}
        </div>
        <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-4 clr-col-xl-3">
            <b>Systems Controlled : </b>{{systemsControlled}}
        </div>
    </div>
    <clr-datagrid>
        <clr-dg-column [clrDgSortBy]="'controlling'" class="control-width">👑</clr-dg-column>
        <clr-dg-column [clrDgField]="'system_name'">System</clr-dg-column>
        <clr-dg-column [clrDgSortBy]="'influence'">Influence</clr-dg-column>
        <clr-dg-column [clrDgField]="'state'">State</clr-dg-column>
        <clr-dg-column [clrDgField]="'happiness'">Happiness</clr-dg-column>
        <clr-dg-column>Active States</clr-dg-column>
        <clr-dg-column>Pending States</clr-dg-column>
        <clr-dg-column>Recovering States</clr-dg-column>
        <clr-dg-column [clrDgSortBy]="'population'">Population</clr-dg-column>
        <clr-dg-column [clrDgSortBy]="'updated_at'">Last Updated At (UTC)</clr-dg-column>

        <clr-dg-placeholder>Unable to fetch data for faction</clr-dg-placeholder>

        <clr-dg-row *clrDgItems="let presence of factionData?.faction_presence">
            <clr-dg-cell class="control-width">
                <ng-container *ngIf="presence.controlling">👑</ng-container>
            </clr-dg-cell>
            <clr-dg-cell><a routerLink="/system/{{presence.system_id}}">{{presence.system_name}}</a></clr-dg-cell>
            <clr-dg-cell>{{(presence.influence * 100).toFixed(2)}}%</clr-dg-cell>
            <clr-dg-cell>{{presence.state}}</clr-dg-cell>
            <clr-dg-cell>{{presence.happiness}}</clr-dg-cell>
            <clr-dg-cell>
                <span class="label label-info" *ngFor="let active of presence.active_states">{{active.state}}</span>
            </clr-dg-cell>
            <clr-dg-cell>
                <span class="label" *ngFor="let pending of presence.pending_states"
                    [ngClass]="{'label-info': pending.trend === 0,'label-success': pending.trend > 0,'label-danger':pending.trend < 0}">{{pending.state}}</span>
            </clr-dg-cell>
            <clr-dg-cell>
                <span class="label" *ngFor="let recovering of presence.recovering_states"
                    [ngClass]="{'label-info': recovering.trend === 0,'label-success': recovering.trend > 0,'label-danger':recovering.trend < 0}">{{recovering.state}}</span>
            </clr-dg-cell>
            <clr-dg-cell>{{presence.system_details.population | number}}</clr-dg-cell>
            <clr-dg-cell>
                {{getUpdatedAtFormatted(presence.updated_at).time}}
                <span class="label"
                    [ngClass]="{'label-info': getUpdatedAtFormatted(presence.updated_at).ageFlag === 0,'label-success': getUpdatedAtFormatted(presence.updated_at).ageFlag < 0,'label-danger':getUpdatedAtFormatted(presence.updated_at).ageFlag > 0}">{{getUpdatedAtFormatted(presence.updated_at).fromNow}}</span>
            </clr-dg-cell>
        </clr-dg-row>
    </clr-datagrid>

    <h3>Conflicts</h3>
    <ng-container
        *ngIf="conflicts.length > 0; then conflictsPresentTemplate; else conflictsAbsentTemplate">
    </ng-container>
    <ng-template #conflictsPresentTemplate>
        <clr-datagrid>
            <clr-dg-column [clrDgField]="'system_name'">System</clr-dg-column>
            <clr-dg-column [clrDgSortBy]="'type'">Conflict Type</clr-dg-column>
            <clr-dg-column [clrDgField]="'status'">Conflict Status</clr-dg-column>
            <clr-dg-column [clrDgField]="'opponent_name'">Opponent Name</clr-dg-column>
            <clr-dg-column [clrDgField]="'stake'">Stake</clr-dg-column>
            <clr-dg-column [clrDgSortBy]="'days_won'">Days Won</clr-dg-column>

            <clr-dg-placeholder>Unable to fetch data for faction</clr-dg-placeholder>

            <clr-dg-row *clrDgItems="let conflict of conflicts">
                <clr-dg-cell><a routerLink="/system/{{conflict.system_id}}">{{conflict.system_name}}</a>
                </clr-dg-cell>
                <clr-dg-cell>{{conflict.type}}</clr-dg-cell>
                <clr-dg-cell>{{conflict.status}}</clr-dg-cell>
                <clr-dg-cell>{{conflict.opponent_name}}</clr-dg-cell>
                <clr-dg-cell>{{conflict.stake}}</clr-dg-cell>
                <clr-dg-cell>{{conflict.days_won}}</clr-dg-cell>
            </clr-dg-row>
        </clr-datagrid>
    </ng-template>
    <ng-template #conflictsAbsentTemplate>
        Faction not in conflict anywhere
    </ng-template>

    <h3>Date Filter</h3>
    <div class="clr-row">
        <form clrForm clrLayout="row">
            <clr-date-container>
                <label>From</label>
                <input type="date" [clrDate]="fromDateFilter" (clrDateChange)="fromDateChange($event)">
            </clr-date-container>
        </form>
        <form clrForm clrLayout="row">
            <clr-date-container>
                <label>To</label>
                <input type="date" [clrDate]="toDateFilter" (clrDateChange)="toDateChange($event)">
            </clr-date-container>
        </form>
    </div>
    <div class="card">
        <div class="card-block">
            <div class="card-title">
                Last {{daysGap}} Days
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-influence-chart [factionData]="factionData"></app-faction-influence-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
        </div>
        <div class="card-block">
            <div class="card-title">
                Last {{daysGap}} Days
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-state-chart [factionData]="factionData"></app-faction-state-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-a-p-r-state-chart [factionData]="factionData" type="active">
                </app-faction-a-p-r-state-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-a-p-r-state-chart [factionData]="factionData" type="pending">
                </app-faction-a-p-r-state-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-a-p-r-state-chart [factionData]="factionData" type="recovering">
                </app-faction-a-p-r-state-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
            <div class="card-text flex-relative" *ngIf="factionData !== undefined">
                <app-faction-happiness-chart [factionData]="factionData"></app-faction-happiness-chart>
                <div class="chart-spinner" *ngIf="chartLoading">
                    <div class="spinner"></div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend-vue/src/components/main/factions/FactionView.vue
<template>
  <div>
    <h1>{{ faction.name }}</h1>
    <v-btn-toggle multiple max=0>
      <v-btn color="primary">
        Monitor Faction
      </v-btn>
      <v-btn color="primary">
        EDDB
      </v-btn>
    </v-btn-toggle>
    <v-row class="pt-8">
      <v-col cols="12" sm="12" md="6" lg="4" xl="3">
        <b>Government : </b>{{ faction.government }}
      </v-col>
      <v-col cols="12" sm="12" md="6" lg="4" xl="3">
        <b>Allegiance : </b>{{ faction.allegiance }}
      </v-col>
      <v-col cols="12" sm="12" md="6" lg="4" xl="3">
        <b>Systems Presence : </b>{{ systemsPresence }}
      </v-col>
      <v-col cols="12" sm="12" md="6" lg="4" xl="3">
        <b>Systems Controlled : </b>{{ systemsControlled }}
      </v-col>
    </v-row>
    <v-form>
      <v-row>
        <v-col cols="12" sm="6">
          <v-text-field v-model="factionFilter" hint="Faction name/state/happiness" label="Filter"></v-text-field>
        </v-col>
      </v-row>
    </v-form>
    <v-data-table
      class="elevation-1"
      :headers="headers"
      :items="system_details"
      :search="factionFilter"
      hide-default-footer
      :loading="loading">
      <template v-slot:item.name="{item}">
        <router-link :to="{ name: 'system-detail', params: { systemId: item.system_id }}">{{
            item.name
          }}
        </router-link>
      </template>
      <template v-slot:item.active_states="{item}">
        <v-chip
          v-for="active_state in item.active_states"
          :key="active_state.state"
          color="blue"
          x-small>
          {{ active_state.state }}
        </v-chip>
      </template>
      <template v-slot:item.pending_states="{item}">
        <v-chip
          v-for="pending_state in item.pending_states"
          :key="pending_state.state"
          :color="getChipColour(pending_state.trend)"
          x-small>
          {{ pending_state.state }}
        </v-chip>
      </template>
      <template v-slot:item.recovering_states="{item}">
        <v-chip
          v-for="recovering_state in item.recovering_states"
          :key="recovering_state.state"
          :color="getChipColour(recovering_state.trend)"
          x-small>
          {{ recovering_state.state }}
        </v-chip>
      </template>
      <template v-slot:item.influence="{item}">
        {{ item.influence.toFixed(2) }}%
      </template>
      <template v-slot:item.updated_at="{item}">
        {{ formatDate(item.updated_at) }}
        <v-chip small :color="item.age_flag">
          {{ item.from_now }}
        </v-chip>
      </template>
    </v-data-table>
    <h2 class="py-8">Conflicts</h2>
    <v-data-table
      dense
      :headers="conflictHeaders"
      :items="conflicts"
      class="elevation-1"
      hide-default-footer
      v-if="conflicts && conflicts.length>0"
    >
      <template v-slot:item.stake="{item}">
        {{ getConflictStakeMessage(item.stake) }}
      </template>
      <template v-slot:item.days_won="{item}">
        <template v-if="item.days_won">
          {{ item.days_won }}
        </template>
        <template v-else>
          0
        </template>
      </template>
    </v-data-table>
    <p v-else-if="loading">Loading...</p>
    <p v-else>Faction not in a conflict anywhere</p>
    <h2 class="py-8">Date Filter</h2>
    <v-row>
      <v-col cols="12" sm="6">
        <v-menu
          ref="datepickerRef"
          v-model="datePickerMenu"
          transition="scale-transition"
          offset-y
          offset-x
          @update:return-value="onChangedFilterDates"
          min-width="auto"
          :close-on-content-click="false"
        >
          <template v-slot:activator="{ on, attrs }">
            <v-text-field
              label="Click to select date range (UTC)"
              prepend-icon="event"
              readonly
              :value="datePickerDisplay"
              v-bind="attrs"
              v-on="on"
            ></v-text-field>
          </template>
          <v-date-picker
            v-model="changedFilterDates"
            range
            :show-current="currentUtcDate"
            show-adjacent-months
          >
            <v-row>
              <v-col cols="12" sm="6">
                <v-btn
                  block
                  text
                  color="error"
                  @click="datePickerMenu = false"
                >
                  Cancel
                </v-btn>
              </v-col>
              <v-col cols="12" sm="6">
                <v-btn
                  block
                  text
                  color="success"
                  @click="$refs.datepickerRef.save(changedFilterDates)"
                >
                  OK
                </v-btn>
              </v-col>
            </v-row>
          </v-date-picker>
        </v-menu>
      </v-col>
    </v-row>
    <v-card>
      <v-card-title>
        Graphs
      </v-card-title>
    </v-card>
  </div>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex'
import moment from 'moment'

export default {
  name: 'FactionView',
  data () {
    return {
      loading: false,
      conflicts: [],
      systemsPresence: 0,
      systemsControlled: 0,
      factionFilter: '',
      conflictsPanel: [],
      filterDates: [],
      changedFilterDates: [],
      datePickerMenu: false,
      currentUtcDate: '',
      dateFormat: 'YYYY-MM-DD',
      headers: [{
        text: '👑',
        value: 'controlling'
      }, {
        text: 'System Name',
        value: 'name'
      }, {
        text: 'Influence',
        value: 'influence',
        filterable: false
      }, {
        text: 'State',
        value: 'state'
      }, {
        text: 'Happiness',
        value: 'happiness'
      }, {
        text: 'Active States',
        value: 'active_states',
        filterable: false,
        sortable: false
      }, {
        text: 'Pending States',
        value: 'pending_states',
        filterable: false,
        sortable: false
      }, {
        text: 'Recovering States',
        value: 'recovering_states',
        filterable: false,
        sortable: false
      }, {
        text: 'Population',
        value: 'population',
        filterable: false
      }, {
        text: 'Last Updated At (UTC)',
        value: 'updated_at',
        filterable: false
      }],
      conflictHeaders: [{
        text: 'System Name',
        value: 'system_name'
      }, {
        text: 'Conflict Type',
        value: 'type'
      }, {
        text: 'Conflict Status',
        value: 'status'
      }, {
        text: 'Opponent Name',
        value: 'opponent_name'
      }, {
        text: 'Stake',
        value: 'stake'
      }, {
        text: 'Days Won',
        value: 'days_won'
      }]
    }
  },
  props: {
    factionId: {
      type: String,
      default: ''
    }
  },
  async created () {
    this.filterDates = [
      moment().subtract(10, 'days').utc().format(this.dateFormat),
      moment().utc().format(this.dateFormat)
    ]
    this.changedFilterDates = this.filterDates
    this.currentUtcDate = moment().utc().format(this.dateFormat)
    await this.checkRedirect()
    this.fetchFactionWithHistoryById()
  },
  computed: {
    ...mapGetters({
      faction: 'friendlyFaction'
    }),
    system_details () {
      return this.faction.faction_presence?.map(system => {
        return {
          ...system,
          controlling: system.system_details.controlling_minor_faction_id === this.faction._id ? '👑' : '',
          influence: system.influence * 100,
          name: system.system_name,
          population: system.system_details.population,
          system_id: system.system_id,
          from_now: moment(system.updated_at).fromNow(true),
          age_flag: this.getChipColour(-(moment().diff(moment(system.updated_at), 'days', true) - 1))
        }
      })
    },
    datePickerDisplay () {
      return `${this.filterDates[0]} - ${this.filterDates[1]}`
    }
  },
  methods: {
    ...mapMutations([
      'setSelectedFaction'
    ]),
    formatDate (date) {
      return moment(date).utc().format('ddd, MMM D, HH:mm:ss')
    },
    getChipColour (value) {
      if (value === 0) {
        return 'blue'
      } else if (value > 0) {
        return 'green'
      } else {
        return 'red'
      }
    },
    onChangedFilterDates (value) {
      if (value) {
        if (moment(value[0], this.dateFormat).isAfter(moment(value[1], this.dateFormat))) {
          value.reverse()
        }
        this.filterDates = [...value]
      }
    },
    getConflictStakeMessage (stake) {
      if (stake) {
        return `${stake} is at stake`
      } else {
        return `Nothing is at stake`
      }
    },
    async checkRedirect () {
      if (this.factionId.toLowerCase().startsWith('eddbid-')) {
        let faction = await this.$store.dispatch('fetchFactionByEddbId', {
          eddbId: this.factionId.slice(7)
        })
        await this.$router.push({ name: 'faction-detail', params: { factionId: faction.docs[0]._id } })
      }
    },
    async fetchFactionWithHistoryById () {
      this.loading = true
      let factionsPaginated = await this.$store.dispatch('fetchFactionWithHistoryById', {
        id: this.factionId,
        timeMin: moment.utc(this.filterDates[0], this.dateFormat),
        timeMax: this.filterDates[1] === moment().format(this.dateFormat) ? moment() : moment(this.filterDates[1], this.dateFormat)
      })
      this.setSelectedFaction(factionsPaginated.docs[0])
      this.conflicts = this.faction.faction_presence.reduce((acc, system) => {
        return acc.concat(system.conflicts)
      }, [])
      this.systemsPresence = this.faction.faction_presence.length
      this.systemsControlled = this.faction.faction_presence.reduce((count, system) => {
        if (system.controlling) {
          return count + 1
        } else {
          return count
        }
      }, 0)
      this.loading = false
    }
  }
}
</script>

<style scoped>

</style>
