// frontend/src/app/eddb_api/overview/eddb-api-overview.component.ts
import { Component, HostBinding } from '@angular/core';
import { Title } from '@angular/platform-browser';

@Component({
    selector: 'app-eddb-api-overview',
    templateUrl: './eddb-api-overview.component.html'
})
export class EddbApiOverviewComponent {
    @HostBinding('class.content-container') contentContainer = true;
    constructor(private titleService: Title) {
        this.titleService.setTitle('EDDB API - Elite BGS');
    }
}

<div class="content-area">
    <h1>The complete RESTful API for EDDB</h1>
    <h3>
        Currently <a href="https://eddb.io/">EDDB</a> is the greatest treasure of information of the galaxy and it is a user
        friendly tool for many pilots. But it lacks an API for developers. Elite BGS is an attempt to fill this gap by providing
        an API for EDDB data sources.
    </h3>
    <h2>API</h2>
    <div class="card">
        <div class="card-title">Access</div>
        <div class="card-text">
            Consumers must make a GET request at any endpoint.
        </div>
    </div>
    <div class="card">
        <div class="card-title">Endpoints</div>
        <div class="card-text">
            <h3>Factions</h3>
            <code>https://eddbapi.kodeblox.com/api/v4/factions?&lt;params&gt;</code>
            <h3>Populated Systems</h3>
            <code>https://eddbapi.kodeblox.com/api/v4/populatedsystems?&lt;params&gt;</code>
            <h3>Stations</h3>
            <code>https://eddbapi.kodeblox.com/api/v4/stations?&lt;params&gt;</code>
            <h3>Systems</h3>
            <code>https://eddbapi.kodeblox.com/api/v4/systems?&lt;params&gt;</code>
        </div>
        <div>
            *Please note that the endpoints have been changed to their own subdomain.
        </div>
    </div>
</div>

// frontend-vue/src/components/docs/eddbApi/EddbApiOverview.vue
<template>
  <div>
    <h1>The complete RESTful API for EDDB</h1>
    <h3>
      Currently <a href="https://eddb.io/">EDDB</a> is the greatest treasure of information of the galaxy and it is a
      user
      friendly tool for many pilots. But it lacks an API for developers. Elite BGS is an attempt to fill this gap by
      providing
      an API for EDDB data sources.
    </h3>
    <h2>API</h2>
    <div class="card">
      <div class="card-title">Access</div>
      <div class="card-text">
        Consumers must make a GET request at any endpoint.
      </div>
    </div>
    <div class="card">
      <div class="card-title">Endpoints</div>
      <div class="card-text">
        <h3>Factions</h3>
        <code>https://eddbapi.kodeblox.com/api/v4/factions?&lt;params&gt;</code>
        <h3>Populated Systems</h3>
        <code>https://eddbapi.kodeblox.com/api/v4/populatedsystems?&lt;params&gt;</code>
        <h3>Stations</h3>
        <code>https://eddbapi.kodeblox.com/api/v4/stations?&lt;params&gt;</code>
        <h3>Systems</h3>
        <code>https://eddbapi.kodeblox.com/api/v4/systems?&lt;params&gt;</code>
      </div>
      <div>
        *Please note that the endpoints have been changed to their own subdomain.
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'EddbApiOverview'
}
</script>

<style scoped>

</style>
