// src/app/elite_bgs_api/overview/elite-bgs-api-overview.component.ts
import { Component, HostBinding } from '@angular/core';

@Component({
    selector: 'app-ebgs-api-overview',
    templateUrl: './elite-bgs-api-overview.component.html'
})
export class EliteBgsApiOverviewComponent {
    @HostBinding('class.content-container') contentContainer = true;
    constructor() { }
}

<div class="content-area">
    <div class="component">
        <h1 style="text-align:left;float:left;">A Historical API</h1>
        <div style="text-align:right;float:right;">
            <a class="btn btn-primary" href="https://www.paypal.me/SayakMukhopadhyay">Donate</a>
        </div>
        <br style="clear:both;">
        <h3>
            For ultimate immersion and BGS control, we require not only the latest data but also historical ones. ELITE BGS API is a
            step in that direction. It stores information which changes regularly in a historical format. Thus, one can always
            look up the events that led to the current Civil War for instance.
        </h3>
        <h2>API</h2>
        <div class="card">
            <div class="card-title">Access</div>
            <div class="card-text">
                Consumers must make a GET request at any endpoint using Basic HTTP authentication with username
                <code>guest</code> and password <code>secret</code>.
            </div>
        </div>
        <div class="card">
            <div class="card-title">Endpoints</div>
            <div class="card-text">
                <h3>Factions</h3>
                <code>http://elitebgs.kodeblox.com/api/ebgs/v1/factions?&lt;params&gt;</code>
                <h3>Systems</h3>
                <code>http://elitebgs.kodeblox.com/api/ebgs/v1/systems?&lt;params&gt;</code>
            </div>
        </div>
    </div>
</div>

// frontend-vue/src/components/docs/eliteBgsApi/EliteBgsApiOverview.vue
<template>
  <div>
    <h1>A Historical API</h1>
    <h3>
      For ultimate immersion and BGS control, we require not only the latest data but also historical ones. ELITE BGS
      API is a
      step in that direction. It stores information which changes regularly in a historical format. Thus, one can always
      look up the events that led to the current Civil War for instance.
    </h3>
    <h2>API</h2>
    <div class="card">
      <div class="card-title">Access</div>
      <div class="card-text">
        Consumers must make a GET request at any endpoint.
      </div>
    </div>
    <div class="card">
      <div class="card-title">Endpoints</div>
      <div class="card-text">
        <h3>Factions</h3>
        <code>https://elitebgs.app/api/ebgs/v5/factions?&lt;params&gt;</code>
        <h3>Systems</h3>
        <code>https://elitebgs.app/api/ebgs/v5/systems?&lt;params&gt;</code>
        <h3>Stations</h3>
        <code>https://elitebgs.app/api/ebgs/v5/stations?&lt;params&gt;</code>
        <h3>Ticks</h3>
        <code>https://elitebgs.app/api/ebgs/v5/ticks?&lt;params&gt;</code>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'EliteBgsApiOverview'
}
</script>

<style scoped>

</style>
