// src/app/about/about.component.ts
import { Component, HostBinding } from '@angular/core';

@Component({
    templateUrl: './about.component.html',
    styleUrls: ['./about.component.scss']
})
export class AboutComponent {
    @HostBinding('class.content-container') contentContainer = true;
    constructor() { }
}

<div class="content-area" style="padding: 0px">
    <div class="content-area">
        <div class="clr-row">
            <!-- Todo: Push and Pull is deprecated -->
            <div class="clr-col-lg-5 clr-col-md-6 clr-col-sm-12 push-md-6 push-lg-7 header-logo">
                <img src="/assets/BGSv1.svg" alt="Elite BGS Logo" />
            </div>
            <div class="clr-col-lg-7 clr-col-md-6 clr-col-sm-12 pull-md-6 pull-lg-5">
                <div class="header-block">
                    <h1>Elite BGS</h1>
                    <p>
                        A tool to track and manage the Background Simulation (BGS) of Elite Dangerous. Visualise
                        influences and states using graphs and monitor factions and systems. Forget spreadsheets!
                    </p>
                    <a class="btn btn-primary" routerLink="/guide">Guide</a>
                    <a class="btn btn-outline" href="https://github.com/SayakMukhopadhyay/elitebgs">Source</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                For Commanders. By a Commander.
            </div>
            <div class="card-block feature-card">
                <div class="clr-row">
                    <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                        <div class="card-img">
                            <clr-icon shape="line-chart" size="128"></clr-icon>
                        </div>
                        <div class="card-title">
                            Graphs
                        </div>
                        <div class="card-text">
                            Visualise influnce in a dynamic graph that is automatically created and updated.
                        </div>
                    </div>
                    <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                        <div class="card-img">
                            <clr-icon shape="display" size="128"></clr-icon>
                        </div>
                        <div class="card-title">
                            Monitor
                        </div>
                        <div class="card-text">
                            Monitor factions and systems in your dashboard.
                        </div>
                    </div>
                    <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                        <div class="card-img">
                            <clr-icon shape="switch" size="128"></clr-icon>
                        </div>
                        <div class="card-title">
                            Pending and Recovering States
                        </div>
                        <div class="card-text">
                            Now you can even check the pending and recovering states of your faction and that too with
                            the current trend.
                        </div>
                    </div>
                    <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                        <div class="card-img">
                            <clr-icon shape="pencil" size="128"></clr-icon>
                        </div>
                        <div class="card-title">
                            Edit System Data
                        </div>
                        <div class="card-text">
                            Authorised users can even edit and update the data for a system. Perfect when you are 20000
                            LY away from home.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h2>Reach me at</h2>
        <div class="clr-row contact-card">
            <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                <a href="https://github.com/SayakMukhopadhyay" class="card clickable">
                    <div class="card-img">
                        <img src="/assets/github-logo.svg" alt="Github Logo" />
                    </div>
                    <div class="card-header">
                        Github Profile
                    </div>
                </a>
            </div>
            <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                <a href="https://discord.gg/0uwCh6R62aQ0eeAX" class="card clickable">
                    <div class="card-img">
                        <img src="/assets/edcd-logo.svg" alt="Github Logo" />
                    </div>
                    <div class="card-header">
                        EDCD Discord Server
                    </div>
                </a>
            </div>
            <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                <a href="https://forums.frontier.co.uk/member.php/136073-Garud" class="card clickable">
                    <div class="card-img">
                        <img src="/assets/ed-logo.svg" alt="Github Logo" />
                    </div>
                    <div class="card-header">
                        Frontier Forums
                    </div>
                </a>
            </div>
            <div class="clr-col-lg-3 clr-col-md-6 clr-col-sm-12">
                <a href="https://discord.gg/YksSXke" class="card clickable">
                    <div class="card-img">
                        <img src="/assets/discord-logo.svg" alt="Github Logo" />
                    </div>
                    <div class="card-header">
                        Elite BGS Discord Server
                    </div>
                </a>
            </div>
        </div>
        <h2>Brought to you By</h2>
        <div class="clr-row clr-justify-content-center">
            <div class="clr-col-lg-3 clr-col-md-3 clr-col-sm-12">
                <div class="self-logo">
                    <img src="/assets/garud-logo.svg" alt="Garud Logo" />
                    <h3>CMDR Garud</h3>
                </div>
            </div>
            <div class="clr-col-lg-3 clr-col-md-2 clr-col-sm-12 clr-align-self-center">
                <div class="ampersand">
                    <img src="/assets/ampersand.svg" alt="Ampersand" />
                </div>
            </div>
            <div class="clr-col-lg-3 clr-col-md-3 clr-col-sm-12">
                <a href="https://knightsofkarma.com" class="self-logo">
                    <img src="/assets/kok-logo.svg" alt="Knights of Karma Logo" />
                    <h3>Knights of Karma</h3>
                </a>
            </div>
        </div>
        <h2>Owner Information</h2>
        <p>Sayak Mukhopadhyay
            <br> Plot No 205
            <br> Hijli Coperative Society
            <br> Kharagpur
            <br> West Bengal - 721306
            <br> India
            <br>
            <a href="mailto:contact@kodeblox.com">contact@kodeblox.com</a>
        </p>
        <h2><a routerLink="/about/termsandconditions">Terms and Conditions</a></h2>
        <p>
            Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and
            be bound by the following terms and conditions of use, which together with our privacy policy govern Elite
            BGS's relationship with you in relation to this website. If you disagree with any part of these terms and
            conditions, please do not use our website.
        </p>
        <p>
            The term 'Elite BGS' or 'me' or 'I' refers to the owner of the website. The term 'you' refers to the user
            or viewer of our website.
        </p>
        <p>The use of this website is subject to the following terms of use:</p>
        <ol>
            <li>The content of the pages of this website is for your general information and use only. It is subject to
                change without notice.</li>
            <li>
                This website uses cookies to manage sessions. No other data is tracked using cookies.
            </li>
            <li>
                Neither I nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
                performance, completeness or suitability of the information and materials found or offered on this
                website for any particular purpose. You acknowledge that such information and materials may contain
                inaccuracies or errors and I expressly exclude liability for any such inaccuracies or errors to the
                fullest extent permitted by law.
            </li>
            <li>
                Your use of any information or materials on this website is entirely at your own risk, for which I
                shall not be liable. It shall be your own responsibility to ensure that any products, services or
                information available through this website meet your specific requirements.
            </li>
            <li>
                All product names, logos, and brands are property of their respective owners. All company, product and
                service names used in this website are for identification purposes only. Use of these names, logos, and
                brands does not imply endorsement or affiliation.
            </li>
            <li>
                From time to time this website may also include links to other websites. These links are provided for
                your convenience to provide further information. They do not signify that we endorse the website(s). We
                have no responsibility for the content of the linked website(s).
            </li>
        </ol>
        <h2><a routerLink="/about/disclaimer">Disclaimer</a></h2>
        <p>
            This website is not an official tool for the game <a href="https://www.elitedangerous.com/">Elite Dangerous</a>
            and is not affiliated with <a href="https://frontier.co.uk/">Frontier Developments</a>. All information
            provided is based on publicly available information and may not be entirely accurate. Elite BGS was created
            using assets and imagery from Elite Dangerous, with the permission of Frontier Developments plc, for
            non-commercial purposes. It is not endorsed by nor reflects the views or opinions of Frontier Developments
            and no employee of Frontier Developments was involved in the making of it.
        </p>
        <p>
            The information contained in this website is for general information purposes only. The information is
            provided by Elite BGS and while I endeavour to keep the information up to date and correct, I make no
            representations or warranties of any kind, express or implied, about the completeness, accuracy,
            reliability, suitability or availability with respect to the website or the information, products,
            services, or related graphics contained on the website for any purpose. Any reliance you place on such
            information is therefore strictly at your own risk.
        </p>
        <p>
            In no event will I be liable for any loss or damage including without limitation, indirect or consequential
            loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in
            connection with, the use of this website.
        </p>
        <p>
            Through this website you are able to link to other websites which are not under the control of Elite BGS. I
            have no control over the nature, content and availability of those sites. The inclusion of any links does
            not necessarily imply a recommendation or endorse the views expressed within them.
        </p>
        <p>
            Every effort is made to keep the website up and running smoothly. However, Elite BGS takes no
            responsibility for, and will not be liable for, the website being temporarily unavailable due to technical
            issues beyond our control.
        </p>
        <h2><a routerLink="/about/privacypolicy">Privacy Policy</a></h2>
        <p>
            This privacy policy has been compiled to better serve those who are concerned with how their 'Personally
            Identifiable Information' (PII) is being used online. PII, as described in US privacy law and information
            security, is information that can be used on its own or with other information to identify, contact, or
            locate a single person, or to identify an individual in context. Please read my privacy policy carefully to
            get a clear understanding of how I collect, use, protect or otherwise handle your Personally Identifiable
            Information in accordance with my website.
        </p>
        <p>
            <strong>What personal information do I collect from the people that visit my website?</strong>
        </p>
        <p>
            When registering on my site your Discord username is collected.
        </p>
        <p>
            <strong> When do I collect information?</strong>
        </p>
        <p>
            I collect minimal information from you when you register on my site.
        </p>
        <p>
            <strong>How do I use your information?</strong>
        </p>
        <p>
            I may use the information I collect from you when you register, surf the website, or use certain other site
            features in the following ways:
        </p>
        <ul>
            <li>
                To personalize your experience and to allow me to deliver the type of content in which you are most
                interested.
            </li>
            <li>
                To follow up with them after correspondence (live chat or email enquiries)
            </li>
        </ul>
        <p>
            <strong>How do I protect your information?</strong>
        </p>
        <p>
            I only provide articles and information. I never ask for credit card numbers. I do not use Malware
            Scanning.
        </p>
        <p>
            Your personal information is contained behind secured networks and is only accessible by me and I am
            required to keep the information confidential. In addition, all sensitive information you supply is
            encrypted via Secure Socket Layer (SSL) technology.
        </p>
        <p>
            I implement a variety of security measures when a user enters, submits, or accesses their information to
            maintain the safety of your personal information.
        </p>
        <p>
            <strong>Do I use 'cookies'?</strong>
        </p>
        <p>
            Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive
            through your Web browser (if you allow) that enables the site's or service provider's systems to recognize
            your browser and capture
        </p>
        <p>
            I use cookies to keep logged in sessions alive between page navigation and understand and save user's
            preferences for future visits.
        </p>
        <p>
            You consent to the use of cookies by using this website. If you don't want to use cookies, you can choose
            to turn off all cookies. You do this through your browser settings. Since browser is a little different,
            look at your browser's Help Menu to learn the correct way to modify your cookies.
        </p>
        <p>
            If you turn cookies off, Some of the features that make your site experience more efficient may not
            function properly.It won't affect the user's experience that make your site experience more efficient and
            may not function properly.
        </p>
        <p>
            <strong>Third-party disclosure</strong>
        </p>
        <p>
            I do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information.
        </p>
        <p>
            <strong>Third-party links</strong>
        </p>
        <p>
            Occasionally, at my discretion, I may include or offer third-party products or services on my website.
            These third-party sites have separate and independent privacy policies. I therefore have no responsibility
            or liability for the content and activities of these linked sites. Nonetheless, I seek to protect the
            integrity of my site and welcome any feedback about these sites.
        </p>
        <p>
            <strong>Google</strong>
        </p>
        <p>
            Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in
            place to provide a positive experience for users.
            <a href="https://support.google.com/adwordspolicy/answer/1316548?hl=en">
                https://support.google.com/adwordspolicy/answer/1316548?hl=en
            </a>
        </p>
        <p>
            I have not enabled Google AdSense on my site but I may do so in the future.
        </p>
        <p>
            <strong>California Online Privacy Protection Act</strong>
        </p>
        <p>
            CalOPPA is the first state law in the nation to require commercial websites and online services to post a
            privacy policy. The law's reach stretches well beyond California to require any person or company in the
            United States (and conceivably the world) that operates websites collecting Personally Identifiable
            Information from California consumers to post a conspicuous privacy policy on its website stating exactly
            the information being collected and those individuals or companies with whom it is being shared. - See more
            at:
            <a href="http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf">
                http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf
            </a>
        </p>
        <p>
            According to CalOPPA, I agree to the following: Users can visit my site anonymously. Once this privacy
            policy is created, I will add a link to it on my home page or as a minimum, on the first significant page
            after entering my website. My Privacy Policy link includes the word 'Privacy' and can easily be found on
            the page specified above.
        </p>
        <p>
            You will be notified of any Privacy Policy changes on my Privacy Policy Page.
        </p>
        <p>
            You can change your personal information by chatting with me through connected Discord account in the
            dedicated Discord server or by sending me an email. You can also delete any information from the system
            using the online portal.
        </p>
        <p>
            <strong>Does my site allow third-party behavioral tracking?</strong>
        </p>
        <p>
            It's also important to note that I do not allow third-party behavioral tracking
        </p>
        <p>
            <strong>COPPA (Children Online Privacy Protection Act)</strong>
        </p>
        <p>
            When it comes to the collection of personal information from children under the age of 13 years old, the
            Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission,
            United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of
            websites and online services must do to protect children's privacy and safety online.
        </p>
        <p>
            I do not specifically market to children under the age of 13 years old.
        </p>
    </div>
    <footer>
        <div class="content-area">
            <h4>
                The site is powered by
            </h4>
            <div class="clr-row clr-align-items-center power">
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://www.mongodb.com/">
                        <img src="/assets/mongodb-logo.svg" alt="MongoDB Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://expressjs.com/">
                        <img src="/assets/express-logo.svg" alt="Express Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://angular.io/">
                        <img src="/assets/angular-logo.svg" alt="Angular Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://nodejs.org/">
                        <img src="/assets/nodejs-logo.svg" alt="Node.js Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://vmware.github.io/clarity/">
                        <img src="/assets/clarity-logo.svg" alt="Clarity Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://www.w3.org/html/">
                        <img src="/assets/html5-logo.svg" alt="HTML5 and CSS3 Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="http://sass-lang.com/">
                        <img src="/assets/sass-logo.svg" alt="Sass Logo" />
                    </a>
                </div>
                <div class="clr-col-md-3 clr-col-sm-6 clr-col-12">
                    <a href="https://studio3t.com/">
                        <img src="/assets/studio-3t-logo.svg" alt="Studio 3T Logo" />
                    </a>
                </div>
            </div>
            <h4>
                Data Networks
            </h4>
            <div class="clr-row clr-align-items-center power">
                <div class="clr-col-md-6 clr-col-sm-12">
                    <a href="https://eddb.io/">
                        <img src="/assets/eddb-white-logo.svg" alt="EDDB Logo" />
                    </a>
                </div>
                <div class="clr-col-md-6 clr-col-sm-12">
                    <a href="https://github.com/EDSM-NET/EDDN">
                        <img src="/assets/eddn-logo.svg" alt="EDDN Logo" />
                    </a>
                </div>
            </div>
            <h4>
                Error reporting tool
            </h4>
            <div class="clr-row bugsnag">
                <div class="clr-col-lg-12 clr-col-md-12 clr-col-sm-12 clr-col-12">
                    <a href="https://www.bugsnag.com/open-source/">
                        <img src="/assets/bugsnag-logo.svg" alt="Bugsnag Logo" />
                    </a>
                </div>
            </div>
            <h4>
                Affiliates
            </h4>
            <div class="clr-row affiliates">
                <div class="clr-col-md-6 clr-col-sm-12">
                    <a rel="nofollow" href="https://affiliate.namecheap.com/?affId=122323">
                        Domain registered at
                        <img src="https://files.namecheap.com/graphics/linkus/234x60-1.gif" alt="Namecheap.com">
                    </a>
                </div>
                <div class="clr-col-md-6 clr-col-sm-12">
                    <a href="https://vpsdime.com/aff.php?aff=1606">
                        Site hosted on
                        <img src="assets/vpsdime-logo.png" alt="VpsDimecom">
                    </a>
                </div>
            </div>
            <div class="notice">
                <p>
                    Elite BGS © 2017
                </p>
                <p>
                    All product names, logos, and brands are property of their respective owners. All company, product
                    and service names used in this website are for identification purposes only. Use of these names,
                    logos, and brands does not imply endorsement or affiliation.
                </p>
            </div>
        </div>
    </footer>
</div>

// frontend-vue/src/components/about/About.vue
<!--
  - KodeBlox Copyright 2020 Sayak Mukhopadhyay
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  - http: //www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<template>
    <div>
        <ed-toolbar>
        </ed-toolbar>
        <v-content>
            <v-container fluid>
                <v-row>
                    <v-col cols="12" lg="5" md="6">
                        <v-img :src="require('@/assets/BGSv1.svg')"
                               alt="Elite BGS Logo"
                               contain
                               height="50vh"
                        />
                    </v-col>
                    <v-col cols="12" lg="7" md="6">
                        <h1 class="display-3">Elite BGS</h1>
                        <p class="mt-6">
                            A tool to track and manage the Background Simulation (BGS) of Elite Dangerous. Visualise
                            influences and states using graphs and monitor factions and systems. Forget spreadsheets!
                        </p>
                        <v-btn class="mr-2" color="primary" to="/guide">Guide</v-btn>
                        <v-btn color="primary" href="https://github.com/SayakMukhopadhyay/elitebgs" outlined
                               target="_blank">
                            Source
                        </v-btn>
                    </v-col>
                </v-row>
                <v-card class="my-5">
                    <v-card-title>
                        <span class="headline">For Commanders. By a Commander.</span>
                    </v-card-title>
                    <v-card-text>
                        <v-row dense>
                            <v-col class="d-flex justify-center flex-column" cols="12" lg="3" md="6">
                                <v-icon size="128">show_chart</v-icon>
                                <div class="text-center mt-2">
                                    <h2 class="mb-2">Graphs</h2>
                                    <div>Visualise influence in a dynamic graph that is automatically created and
                                        updated.
                                    </div>
                                </div>
                            </v-col>
                            <v-col class="d-flex justify-center flex-column" cols="12" lg="3" md="6">
                                <v-icon size="128" class="material-icons-outlined">
                                    screen_search_desktop
                                </v-icon>
                                <div class="text-center mt-2">
                                    <h2 class="mb-2">Monitor</h2>
                                    <div>Monitor factions and systems in your dashboard.</div>
                                </div>
                            </v-col>
                            <v-col class="d-flex justify-center flex-column" cols="12" lg="3" md="6">
                                <v-icon size="128">compare_arrows</v-icon>
                                <div class="text-center mt-2">
                                    <h2 class="mb-2">Pending and Recovering States</h2>
                                    <div>Now you can even check the pending and recovering states of your faction and
                                        that too with the current trend.
                                    </div>
                                </div>
                            </v-col>
                            <v-col class="d-flex justify-center flex-column" cols="12" lg="3" md="6">
                                <v-icon size="128">alarm</v-icon>
                                <div class="text-center mt-2">
                                    <h2 class="mb-2">Tick</h2>
                                    <div>Get the latest information about the BGS tick.</div>
                                </div>
                            </v-col>
                        </v-row>
                    </v-card-text>
                </v-card>
                <h2>Reach me at</h2>
                <v-row>
                    <v-col cols="12" lg="3" md="6">
                        <v-card class="pt-5 card-img" href="https://github.com/SayakMukhopadhyay">
                            <v-img :src="require('@/assets/github-logo.svg')"
                                   alt="Github Logo"
                                   contain
                                   height="50%"
                                   width="50%"/>
                            <v-card-text>
                                Github Profile
                            </v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" lg="3" md="6">
                        <v-card class="pt-5 card-img" href="https://discord.gg/0uwCh6R62aQ0eeAX">
                            <v-img :src="require('@/assets/edcd-logo.svg')"
                                   alt="EDCD Logo"
                                   contain
                                   height="50%"
                                   width="50%"/>
                            <v-card-text>
                                EDCD Discord Server
                            </v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" lg="3" md="6">
                        <v-card class="pt-5 card-img" href="https://forums.frontier.co.uk/member.php/136073-Garud">
                            <v-img :src="require('@/assets/ed-logo.svg')"
                                   alt="Elite Dangerous Logo"
                                   contain
                                   height="50%"
                                   width="50%"/>
                            <v-card-text>
                                Frontier Forums
                            </v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" lg="3" md="6">
                        <v-card class="pt-5 card-img" href="https://discord.gg/YksSXke">
                            <v-img :src="require('@/assets/discord-logo.svg')"
                                   alt="Discord Logo"
                                   contain
                                   height="50%"
                                   width="50%"/>
                            <v-card-text>
                                Elite Shots Discord Server
                            </v-card-text>
                        </v-card>
                    </v-col>
                </v-row>
                <h2>Brought to you By</h2>
                <v-row justify="center">
                    <v-col class="card-img" cols="12" lg="3" md="3" sm="12">
                        <v-img :src="require('@/assets/garud-logo.svg')"
                               alt="Garud Logo"
                               contain
                               height="50%"
                               width="50%"/>
                        <h3>CMDR Garud</h3>
                    </v-col>
                    <v-col class="card-img" cols="12" lg="3" md="2" sm="12">
                        <v-img :src="require('@/assets/ampersand.svg')"
                               alt="Ampersand"
                               contain
                               height="50%"
                               width="50%"/>
                    </v-col>
                    <v-col cols="12" lg="3" md="3" sm="12">
                        <a class="card-img" href="https://knightsofkarma.com" target="_blank">
                            <v-img :src="require('@/assets/kok-logo.svg')"
                                   alt="Knights of Karma Logo"
                                   contain
                                   height="50%"
                                   width="50%"/>
                            <h3>Knights of Karma</h3>
                        </a>
                    </v-col>
                </v-row>
                <owner-info/>
                <h2>
                    <router-link to="/about/termsandconditions">Terms and Conditions</router-link>
                </h2>
                <tandc-text/>
                <h2>
                    <router-link to="/about/disclaimer">Disclaimer</router-link>
                </h2>
                <disclaimer-text/>
                <h2>
                    <router-link to="/about/privacypolicy">Privacy Policy</router-link>
                </h2>
                <privacy-policy-text/>
            </v-container>
            <v-footer>
                <v-row class="pt-4 pl-4">
                    <h4>
                        The site is powered by
                    </h4>
                </v-row>
                <v-row style="width: 100%" justify="center" align="center">
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://www.mongodb.com/">
                            <v-img contain src="@/assets/mongodb-logo.svg" alt="MongoDB Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://expressjs.com/">
                            <v-img contain src="@/assets/express-logo.svg" alt="Express Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://vuejs.org/">
                            <v-img contain src="@/assets/vuejs-logo.svg" alt="Vue.js Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://nodejs.org/">
                            <v-img contain src="@/assets/nodejs-logo.svg" alt="Node.js Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://vuetifyjs.com/en/">
                            <v-img contain src="@/assets/vuetify-logo.svg" alt="Vuetify Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://www.w3.org/html/">
                            <v-img contain src="@/assets/html5-logo.svg" alt="HTML5 and CSS3 Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="http://sass-lang.com/">
                            <v-img contain src="@/assets/sass-logo.svg" alt="Sass Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href=" https://www.jetbrains.com/?from=elitebgs">
                            <v-img contain src="@/assets/jetbrains-logo.svg" alt="JetBrains Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://studio3t.com/">
                            <v-img contain src="@/assets/studio-3t-logo.png" alt="Studio 3T Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://eddb.io/">
                            <v-img contain src="@/assets/eddb-white-logo.svg" alt="EDDB Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://github.com/EDSM-NET/EDDN">
                            <v-img contain src="@/assets/eddn-logo.svg" alt="EDDN Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://www.bugsnag.com/open-source/">
                            <v-img contain src="@/assets/bugsnag-logo.svg" alt="Bugsnag Logo"/>
                        </a>
                    </v-col>
                    <v-col cols="12" lg="2" md="3" sm="6" xs="12">
                        <a href="https://www.cloudflare.com/">
                            <v-img contain src="@/assets/cloudflare-logo.svg" alt="Cloudflare Logo"/>
                        </a>
                    </v-col>
                </v-row>
                <v-row justify="center" align="center">
                    <v-col cols="12" md="6" sm="12">
                        <a rel="nofollow" href="https://affiliate.namecheap.com/?affId=122323">
                            Domain registered at
                            <img src="@/assets/namecheap-logo.svg" alt="Namecheap.com"/>
                        </a>
                    </v-col>
                    <v-col cols="12" md="6" sm="12">
                        <a href="https://www.hetzner.com/">
                            Site hosted on
                            <img src="@/assets/hetzner-logo.svg" alt="Hetzner"/>
                        </a>
                    </v-col>
                </v-row>
                <div class="notice">
                    <p>
                        Elite BGS © 2021
                    </p>
                    <p>
                        All product names, logos, and brands are property of their respective owners. All company,
                        product
                        and service names used in this website are for identification purposes only. Use of these names,
                        logos, and brands does not imply endorsement or affiliation.
                    </p>
                </div>
            </v-footer>
        </v-content>
    </div>
</template>

<script>
import Toolbar from '@/components/Toolbar'
import OwnerInfo from '@/components/about/OwnerInfo'
import TAndCText from '@/components/about/TAndCText'
import DisclaimerText from '@/components/about/DisclaimerText'
import PrivacyPolicyText from '@/components/about/PrivacyPolicyText'

export default {
  name: 'About',
  components: {
    'ed-toolbar': Toolbar,
    'owner-info': OwnerInfo,
    'tandc-text': TAndCText,
    'disclaimer-text': DisclaimerText,
    'privacy-policy-text': PrivacyPolicyText
  }
}
</script>

<style scoped>
.card-img {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.card-img .v-card__text {
    text-align: center;
}
</style>
